// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mempool.proto

package mempoolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MempoolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MempoolMessage_BatchMessage
	//	*MempoolMessage_ReqMessage
	Msg           isMempoolMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolMessage) Reset() {
	*x = MempoolMessage{}
	mi := &file_mempool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolMessage) ProtoMessage() {}

func (x *MempoolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolMessage.ProtoReflect.Descriptor instead.
func (*MempoolMessage) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{0}
}

func (x *MempoolMessage) GetMsg() isMempoolMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MempoolMessage) GetBatchMessage() *MempoolMessage_Batch {
	if x != nil {
		if x, ok := x.Msg.(*MempoolMessage_BatchMessage); ok {
			return x.BatchMessage
		}
	}
	return nil
}

func (x *MempoolMessage) GetReqMessage() *MempoolMessage_Request {
	if x != nil {
		if x, ok := x.Msg.(*MempoolMessage_ReqMessage); ok {
			return x.ReqMessage
		}
	}
	return nil
}

type isMempoolMessage_Msg interface {
	isMempoolMessage_Msg()
}

type MempoolMessage_BatchMessage struct {
	BatchMessage *MempoolMessage_Batch `protobuf:"bytes,1,opt,name=BatchMessage,proto3,oneof"`
}

type MempoolMessage_ReqMessage struct {
	ReqMessage *MempoolMessage_Request `protobuf:"bytes,2,opt,name=ReqMessage,proto3,oneof"`
}

func (*MempoolMessage_BatchMessage) isMempoolMessage_Msg() {}

func (*MempoolMessage_ReqMessage) isMempoolMessage_Msg() {}

type MempoolMessage_Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []byte                 `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolMessage_Batch) Reset() {
	*x = MempoolMessage_Batch{}
	mi := &file_mempool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolMessage_Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolMessage_Batch) ProtoMessage() {}

func (x *MempoolMessage_Batch) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolMessage_Batch.ProtoReflect.Descriptor instead.
func (*MempoolMessage_Batch) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MempoolMessage_Batch) GetBatch() []byte {
	if x != nil {
		return x.Batch
	}
	return nil
}

type MempoolMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missing       [][]byte               `protobuf:"bytes,1,rep,name=missing,proto3" json:"missing,omitempty"`
	Origin        []byte                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolMessage_Request) Reset() {
	*x = MempoolMessage_Request{}
	mi := &file_mempool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolMessage_Request) ProtoMessage() {}

func (x *MempoolMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolMessage_Request.ProtoReflect.Descriptor instead.
func (*MempoolMessage_Request) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MempoolMessage_Request) GetMissing() [][]byte {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *MempoolMessage_Request) GetOrigin() []byte {
	if x != nil {
		return x.Origin
	}
	return nil
}

var File_mempool_proto protoreflect.FileDescriptor

const file_mempool_proto_rawDesc = "" +
	"\n" +
	"\rmempool.proto\x12\amempool\"\xfb\x01\n" +
	"\x0eMempoolMessage\x12C\n" +
	"\fBatchMessage\x18\x01 \x01(\v2\x1d.mempool.MempoolMessage.BatchH\x00R\fBatchMessage\x12A\n" +
	"\n" +
	"ReqMessage\x18\x02 \x01(\v2\x1f.mempool.MempoolMessage.RequestH\x00R\n" +
	"ReqMessage\x1a\x1d\n" +
	"\x05Batch\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\fR\x05batch\x1a;\n" +
	"\aRequest\x12\x18\n" +
	"\amissing\x18\x01 \x03(\fR\amissing\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\fR\x06originB\x05\n" +
	"\x03msgB\rZ\v./mempoolpbb\x06proto3"

var (
	file_mempool_proto_rawDescOnce sync.Once
	file_mempool_proto_rawDescData []byte
)

func file_mempool_proto_rawDescGZIP() []byte {
	file_mempool_proto_rawDescOnce.Do(func() {
		file_mempool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mempool_proto_rawDesc), len(file_mempool_proto_rawDesc)))
	})
	return file_mempool_proto_rawDescData
}

var file_mempool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mempool_proto_goTypes = []any{
	(*MempoolMessage)(nil),         // 0: mempool.MempoolMessage
	(*MempoolMessage_Batch)(nil),   // 1: mempool.MempoolMessage.Batch
	(*MempoolMessage_Request)(nil), // 2: mempool.MempoolMessage.Request
}
var file_mempool_proto_depIdxs = []int32{
	1, // 0: mempool.MempoolMessage.BatchMessage:type_name -> mempool.MempoolMessage.Batch
	2, // 1: mempool.MempoolMessage.ReqMessage:type_name -> mempool.MempoolMessage.Request
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mempool_proto_init() }
func file_mempool_proto_init() {
	if File_mempool_proto != nil {
		return
	}
	file_mempool_proto_msgTypes[0].OneofWrappers = []any{
		(*MempoolMessage_BatchMessage)(nil),
		(*MempoolMessage_ReqMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mempool_proto_rawDesc), len(file_mempool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mempool_proto_goTypes,
		DependencyIndexes: file_mempool_proto_depIdxs,
		MessageInfos:      file_mempool_proto_msgTypes,
	}.Build()
	File_mempool_proto = out.File
	file_mempool_proto_goTypes = nil
	file_mempool_proto_depIdxs = nil
}
