// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: consensus.proto

package consensuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ConsensusMessage_Testfield
	//	*ConsensusMessage_Proposal
	Message       isConsensusMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	mi := &file_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage.ProtoReflect.Descriptor instead.
func (*ConsensusMessage) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusMessage) GetMessage() isConsensusMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsensusMessage) GetTestfield() *ConsensusMessage_Test {
	if x != nil {
		if x, ok := x.Message.(*ConsensusMessage_Testfield); ok {
			return x.Testfield
		}
	}
	return nil
}

func (x *ConsensusMessage) GetProposal() *ConsensusMessage_Propose {
	if x != nil {
		if x, ok := x.Message.(*ConsensusMessage_Proposal); ok {
			return x.Proposal
		}
	}
	return nil
}

type isConsensusMessage_Message interface {
	isConsensusMessage_Message()
}

type ConsensusMessage_Testfield struct {
	Testfield *ConsensusMessage_Test `protobuf:"bytes,1,opt,name=testfield,proto3,oneof"`
}

type ConsensusMessage_Proposal struct {
	Proposal *ConsensusMessage_Propose `protobuf:"bytes,2,opt,name=proposal,proto3,oneof"`
}

func (*ConsensusMessage_Testfield) isConsensusMessage_Message() {}

func (*ConsensusMessage_Proposal) isConsensusMessage_Message() {}

type ConsensusMessage_Test struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messagetext   string                 `protobuf:"bytes,1,opt,name=messagetext,proto3" json:"messagetext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage_Test) Reset() {
	*x = ConsensusMessage_Test{}
	mi := &file_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage_Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage_Test) ProtoMessage() {}

func (x *ConsensusMessage_Test) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage_Test.ProtoReflect.Descriptor instead.
func (*ConsensusMessage_Test) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConsensusMessage_Test) GetMessagetext() string {
	if x != nil {
		return x.Messagetext
	}
	return ""
}

type ConsensusMessage_Propose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         string                 `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage_Propose) Reset() {
	*x = ConsensusMessage_Propose{}
	mi := &file_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage_Propose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage_Propose) ProtoMessage() {}

func (x *ConsensusMessage_Propose) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage_Propose.ProtoReflect.Descriptor instead.
func (*ConsensusMessage_Propose) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConsensusMessage_Propose) GetEmpty() string {
	if x != nil {
		return x.Empty
	}
	return ""
}

var File_consensus_proto protoreflect.FileDescriptor

const file_consensus_proto_rawDesc = "" +
	"\n" +
	"\x0fconsensus.proto\x12\tconsensus\"\xed\x01\n" +
	"\x10ConsensusMessage\x12@\n" +
	"\ttestfield\x18\x01 \x01(\v2 .consensus.ConsensusMessage.TestH\x00R\ttestfield\x12A\n" +
	"\bproposal\x18\x02 \x01(\v2#.consensus.ConsensusMessage.ProposeH\x00R\bproposal\x1a(\n" +
	"\x04Test\x12 \n" +
	"\vmessagetext\x18\x01 \x01(\tR\vmessagetext\x1a\x1f\n" +
	"\aPropose\x12\x14\n" +
	"\x05empty\x18\x01 \x01(\tR\x05emptyB\t\n" +
	"\amessageB\x0fZ\r./consensuspbb\x06proto3"

var (
	file_consensus_proto_rawDescOnce sync.Once
	file_consensus_proto_rawDescData []byte
)

func file_consensus_proto_rawDescGZIP() []byte {
	file_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)))
	})
	return file_consensus_proto_rawDescData
}

var file_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_consensus_proto_goTypes = []any{
	(*ConsensusMessage)(nil),         // 0: consensus.ConsensusMessage
	(*ConsensusMessage_Test)(nil),    // 1: consensus.ConsensusMessage.Test
	(*ConsensusMessage_Propose)(nil), // 2: consensus.ConsensusMessage.Propose
}
var file_consensus_proto_depIdxs = []int32{
	1, // 0: consensus.ConsensusMessage.testfield:type_name -> consensus.ConsensusMessage.Test
	2, // 1: consensus.ConsensusMessage.proposal:type_name -> consensus.ConsensusMessage.Propose
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consensus_proto_init() }
func file_consensus_proto_init() {
	if File_consensus_proto != nil {
		return
	}
	file_consensus_proto_msgTypes[0].OneofWrappers = []any{
		(*ConsensusMessage_Testfield)(nil),
		(*ConsensusMessage_Proposal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_proto_rawDesc), len(file_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_proto_depIdxs,
		MessageInfos:      file_consensus_proto_msgTypes,
	}.Build()
	File_consensus_proto = out.File
	file_consensus_proto_goTypes = nil
	file_consensus_proto_depIdxs = nil
}
